# Generated by Django 4.1.3 on 2022-11-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_application', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo_application.todo')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
            },
        ),
    ]
