# Generated by Django 4.1.3 on 2022-11-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_application', '0004_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='description',
        ),
    ]
